### ISSUE TITLE
Chokes on large files

### ISSUE THREAD

**Issue by shirotech** [AlexxNB/svelte-docs#13]
It seems files larger than 66K will give this kind of error:

```
[!] (plugin svelte) RangeError: Maximum call stack size exceeded
src/pages/modules/core/changelog.md
RangeError: Maximum call stack size exceeded
    at /Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:581:10
    at /Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:226:10
    at handle (/Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:70:17)
    at /Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:248:18
    at Array.map (<anonymous>)
    at handle_body (/Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:247:21)
    at Program (/Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:318:10)
    at handle (/Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:70:17)
    at print (/Volumes/Projects/Projects/docs/node_modules/svelte/node_modules/code-red/dist/code-red.mjs:1413:17)
    at Component.generate (/Volumes/Projects/Projects/docs/node_modules/svelte/src/compiler/compile/Component.ts:316:9)
```

**Comment by AlexxNB** [comment]
Looks like it is code-red issue. 66K per md file, you mean?

**Comment by shirotech** [comment]
Yeah that is right, this if for an .md file. I'm not sure what is using `code-red` as I can't find it in the lock file.

**Comment by AlexxNB** [comment]
Svelte-compiler - see the last line

**Comment by AlexxNB** [comment]
I'm not sure is there any limit of the html elements per svelte components. I think, better way to split file and import those  parts into it

**Comment by shirotech** [comment]
Cool was just doing some testing, not really needed. I can link the file for external for now. Having said that large files are having problems loading on the UI side as well as loading everything in memory and then routing it.

**Comment by AlexxNB** [comment]
I think the problem is not filesize itself but number of html-elements after  markdown code processing. Could you share this file, I'll do some tests.

**Comment by shirotech** [comment]
@AlexxNB Unfortunately it is a changelog for framework without our org so I won't be able to share it. But the React one is quite large as well and have the same issue view-source:https://raw.githubusercontent.com/facebook/react/master/CHANGELOG.md

**Comment by shirotech** [comment]
Looks like they are already on to it, more info can be from this issue https://github.com/sveltejs/svelte/issues/4694
