### ISSUE TITLE
Could not find language example

### ISSUE THREAD

**Issue by babycourageous** [AlexxNB/svelte-docs#17]
Hi there

I am having trouble with integrating svelte-docs. In one of my files in `components` directory I use the `example` block as per docs. I get the following error: 

```
Could not find the language 'example', did you forget to load/include a language module?
[!] (plugin svelte) Error: Unknown language: "example"
Please report this to https://github.com/markedjs/marked.
src/pages/components/accordion.md
Error: Unknown language: "example"
Please report this to https://github.com/markedjs/marked.
    at Object.highlight (/stretch-svelte-docs/node_modules/highlight.js/lib/highlight.js:742:13)
    at Object.highlight (/stretch-svelte-docs/node_modules/@svelte-docs/core/rollup.config.js:541:25)
    at Renderer.code (/stretch-svelte-docs/node_modules/marked/src/Renderer.js:18:32)
    at Parser.parse (/stretch-svelte-docs/node_modules/marked/src/Parser.js:74:32)
    at Function.parse (/stretch-svelte-docs/node_modules/marked/src/Parser.js:27:19)
    at marked (/stretch-svelte-docs/node_modules/marked/src/marked.js:108:19)
    at markup (/stretch-svelte-docs/node_modules/svelte-preprocess-markdown/dist/index.js:1:5259)
    at preprocess (/stretch-svelte-docs/node_modules/svelte/src/compiler/preprocess/index.ts:86:27)
```

I have added to config : 

```
const {markdown} = require('svelte-preprocess-markdown')

module.exports = {
    // if you will serve docs in subdirictory use '/subdir/'
    basepath: '/',

    // theme 
    theme: 'default',

    title: {
        // constant part of page title
        main: 'Stretch UI',

        // use first header's content as a part of page's title 
        // it looks for `# Header` and `## Header` on the current page
        header: true,
    },    

    // URL to your favicon
    favicon: 'static/favicon.png',
 
    pathes: {
        // directory for files, generated in development mode 
        dev: '__DOCS__/dev',

        // directory for builted documentaton
        build: '__DOCS__/dist',
    },
    
    aliases:{

    },
    
    preprocess: [

                 markdown({filetype: 'svelte'}),

    ]

}
```

Do I also need to create a `rollup.config.js`? There wasn't one installed when I initialized the `svelte-docs` project so I assumed it is not needed.

Thanks!

**Comment by AlexxNB** [comment]
Do you use `example` block inside other `example` block?
Can I look the `accrodion.md` file content?

**Comment by babycourageous** [comment]
Hi @AlexxNB -

I got it working - I think it was how the imported components were referencing each other.
I resolve svelte files without `.svelte` extension in my projects. I think the missing extensions in the components were throwing things off. The error is gone. 

But now I am running into a different problem. I'll open a new issue to keep things separate. I'll close this as well.
