### ISSUE TITLE
Error resolving component dependencies

### ISSUE THREAD

**Issue by babycourageous** [AlexxNB/svelte-docs#18]
Hi there

I'm running into an issue resolving dependencies in a component used in an example block.

Say I have a component `Button.svelte` that imports a function from a relative file `utils.js`. 

```
<script>
  import { makeThing } from "./utils.js"
  const thing = makeThing()
</script>

<button>
  <slot />
</button>
```

Then used in an example block (Button is aliased as explained in docs)

```
## Usage

```example
<script>
import Button from 'Button.svelte'
</script>

<Button>default</Button>
```

 it throws this error: 

```
[!] Error: Could not resolve './utils.js' from Button.svelte
Error: Could not resolve './utils.js' from Button.svelte
    at error (svelte-docs/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at ModuleLoader.handleResolveId (svelte-docs/node_modules/rollup/dist/shared/node-entry.js:12410:24)
    at ModuleLoader.<anonymous> (svelte-docs/node_modules/rollup/dist/shared/node-entry.js:12298:30)
    at Generator.next (<anonymous>)
    at fulfilled (svelte-docs/node_modules/rollup/dist/shared/node-entry.js:38:28)
```

This error only occurs when using example block; not when importing at the top of file and using standalone as in Counter used here: https://alexxnb.github.io/svelte-docs/writing/mdsv.

Thanks!

**Comment by AlexxNB** [comment]
Please update on @svelte-docs/core@0.10.5

**Comment by babycourageous** [comment]
That did it!

Thanks so much for the speedy update. Glad it was an easy fix for you!
