### ISSUE TITLE
Build error when using "export { ... }" syntax in components

### ISSUE THREAD

**Issue by mattjennings** [AlexxNB/svelte-docs#9]
First off, thanks for making this. It's been a wonderful and smooth experience to use.

I have a component that exports a prop `with`, which is a reserved keyword, so `export let with` does not work. To workaround that, I use the following syntax:

```js
  let _with
  export { _with as with }
```

it's a little hacky... but it is valid and works. However, if I try to use the properties table with that component

````
```properties
./path/to/my/component.svelte
```
````

it leads to the following error when starting the server:

```
[!] (plugin svelte) TypeError: Cannot read property 'declarations' of null
src/pages/components/arcade-collider.md
TypeError: Cannot read property 'declarations' of null
    at node.body.reduce (/Users/mattjennings/dev/svelte-phaser/docs/node_modules/@svelte-docs/core/rollup.config.js:610:37)
    at Array.reduce (<anonymous>)
    at parseJS (/Users/mattjennings/dev/svelte-phaser/docs/node_modules/@svelte-docs/core/rollup.config.js:606:22)
    at getInterface (/Users/mattjennings/dev/svelte-phaser/docs/node_modules/@svelte-docs/core/rollup.config.js:575:22)
    at /Users/mattjennings/dev/svelte-phaser/docs/node_modules/@svelte-docs/core/rollup.config.js:666:17
    at String.replace (<anonymous>)
    at getBlocks.forEach.block (/Users/mattjennings/dev/svelte-phaser/docs/node_modules/@svelte-docs/core/rollup.config.js:766:19)
    at Array.forEach (<anonymous>)
    at replaceBuiltins (/Users/mattjennings/dev/svelte-phaser/docs/node_modules/@svelte-docs/core/rollup.config.js:752:19)
    at markup (/Users/mattjennings/dev/svelte-phaser/docs/node_modules/@svelte-docs/core/rollup.config.js:732:27)
```

I kind of expected that it wouldn't properly pick up the prop's documentation anyway, but preventing a crash would at least be good.

**Comment by AlexxNB** [comment]
Added suport of such type of exorts. Please, update to `@svelte-docs/core@0.10.0`

**Comment by mattjennings** [comment]
awesome! thanks for the quick fix!
